change hb_stat to use .reencode

diff --git a/hb_stat b/hb_stat
--- a/hb_stat
+++ b/hb_stat
@@ -2,29 +2,34 @@
 
 if [ $# -ne 1 ]; then
     echo "Invalid Usage.";
-    echo "Usage: hb_stat [file]";
+    echo "Usage: hb_stat [directory]";
     exit 1;
 fi;
 
-if  ! [ -f $1 ]; then
-    echo "Error: $1 does not exist.";
+if  ! [ -d $1 ]; then
+    echo "Error: $1 does not exist/is not a directory.";
     exit 1;
+fi;
+
+if ! [ -f $1/.reencode ]; then
+   echo "Error: $1 does not contain the reencode file list, run 'find_all'";
+   exit 1;
 fi;
 
 printf "Complete: ";
-cat $1 | while read i; do if ! [ -f $i ] && [ -f $i.conv.mkv ]; then echo $i; fi; done | wc -l;
+cat $1/.reencode | while read i; do if ! [ -f $1/$i ] && [ -f $1/$i.conv.mkv ]; then echo $i; fi; done | wc -l;
 
 printf "Remaining: ";
-cat $1 | while read i; do if [ -f $i ] && ! [ -f $i.conv.mkv ] ; then echo $i; fi; done | wc -l 
+cat $1/.reencode | while read i; do if [ -f $1/$i ] && ! [ -f $1/$i.conv.mkv ] ; then echo $i; fi; done | wc -l 
 echo;
 
 echo "Finished: ";
-cat $1 | while read i; do if ! [ -f $i ] && [ -f $i.conv.mkv ]; then echo $i; fi; done | tail -n 5;
+cat $1/.reencode | while read i; do if ! [ -f $1/$i ] && [ -f $1/$i.conv.mkv ]; then echo $i; fi; done | tail -n 5;
 echo;
 
 echo "Current: ";
-cat $1 | while read i; do if [ -f $i ] && [ -f $i.conv.mkv ]; then echo $i; fi; done;
+cat $1/.reencode | while read i; do if [ -f $1/$i ] && [ -f $1/$i.conv.mkv ]; then echo $i; fi; done;
 echo;
 
 echo "Next: ";
-cat $1 | while read i; do if [ -f $i ] && ! [ -f $i.conv.mkv ] ; then echo $i; fi; done | head -n 5;
+cat $1/.reencode | while read i; do if [ -f $1/$i ] && ! [ -f $1/$i.conv.mkv ] ; then echo $i; fi; done | head -n 5;
